# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jared\OneDrive\Documentos\OBEJETOS\PharmacyProject\addprod.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(620, 480)
        Dialog.setStyleSheet("background-color: rgb(23, 136, 211);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(120, 40, 391, 91))
        self.label.setStyleSheet("font: 75 24pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 190, 141, 41))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.nameinput = QtWidgets.QLineEdit(Dialog)
        self.nameinput.setGeometry(QtCore.QRect(152, 190, 111, 31))
        self.nameinput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nameinput.setObjectName("nameinput")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(300, 180, 171, 41))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.stockinput = QtWidgets.QLineEdit(Dialog)
        self.stockinput.setGeometry(QtCore.QRect(152, 230, 111, 31))
        self.stockinput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stockinput.setObjectName("stockinput")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(310, 310, 151, 41))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.taxinput = QtWidgets.QLineEdit(Dialog)
        self.taxinput.setGeometry(QtCore.QRect(152, 270, 111, 31))
        self.taxinput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.taxinput.setObjectName("taxinput")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(50, 230, 171, 41))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Arial\";")
        self.label_7.setObjectName("label_7")
        self.presinput = QtWidgets.QLineEdit(Dialog)
        self.presinput.setGeometry(QtCore.QRect(470, 190, 113, 31))
        self.presinput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.presinput.setObjectName("presinput")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(310, 220, 151, 41))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Arial\";")
        self.label_8.setObjectName("label_8")
        self.costinput = QtWidgets.QLineEdit(Dialog)
        self.costinput.setGeometry(QtCore.QRect(470, 230, 113, 31))
        self.costinput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.costinput.setObjectName("costinput")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(310, 260, 151, 41))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.saleinput = QtWidgets.QLineEdit(Dialog)
        self.saleinput.setGeometry(QtCore.QRect(470, 270, 113, 31))
        self.saleinput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.saleinput.setObjectName("saleinput")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(50, 270, 141, 41))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Arial\";")
        self.label_10.setObjectName("label_10")
        self.labinput = QtWidgets.QLineEdit(Dialog)
        self.labinput.setGeometry(QtCore.QRect(470, 310, 113, 31))
        self.labinput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labinput.setObjectName("labinput")
        self.backbutton = QtWidgets.QPushButton(Dialog)
        self.backbutton.setGeometry(QtCore.QRect(500, 420, 93, 28))
        self.backbutton.setStyleSheet("background-color: rgb(167, 168, 167);\n"
"background-color: rgb(156, 208, 93);\n"
"color: rgb(255, 255, 255);")
        self.backbutton.setObjectName("backbutton")
        self.donebutton = QtWidgets.QPushButton(Dialog)
        self.donebutton.setGeometry(QtCore.QRect(260, 420, 93, 28))
        self.donebutton.setStyleSheet("background-color: rgb(156, 208, 93);\n"
"color: rgb(255, 255, 255);")
        self.donebutton.setObjectName("donebutton")
        self.expdate = QtWidgets.QLineEdit(Dialog)
        self.expdate.setGeometry(QtCore.QRect(152, 310, 111, 31))
        self.expdate.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.expdate.setObjectName("expdate")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(10, 310, 181, 41))
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Arial\";")
        self.label_11.setObjectName("label_11")
        self.label_11.raise_()
        self.label_10.raise_()
        self.label_7.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.nameinput.raise_()
        self.label_5.raise_()
        self.stockinput.raise_()
        self.label_6.raise_()
        self.taxinput.raise_()
        self.presinput.raise_()
        self.label_8.raise_()
        self.costinput.raise_()
        self.label_9.raise_()
        self.saleinput.raise_()
        self.labinput.raise_()
        self.backbutton.raise_()
        self.donebutton.raise_()
        self.expdate.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Add a Product</p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Name:</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Presentation: </span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Laboratory:</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Stock:</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Cost Value:</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Sale Value:</span></p></body></html>"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">TAX:</span></p></body></html>"))
        self.backbutton.setText(_translate("Dialog", "Back to Menu"))
        self.donebutton.setText(_translate("Dialog", "Done"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Exp Date:</span></p></body></html>"))
