# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jared\OneDrive\Documentos\OBEJETOS\PharmacyProject\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 900)
        Dialog.setSizeIncrement(QtCore.QSize(50, 50))
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"background-color: rgb(23, 136, 211);")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 180, 171, 71))
        self.label_2.setStyleSheet("font-size:15pt;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 260, 171, 81))
        self.label_3.setStyleSheet("font-size:15pt;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_3.setObjectName("label_3")
        self.username_input = QtWidgets.QLineEdit(Dialog)
        self.username_input.setGeometry(QtCore.QRect(210, 200, 351, 41))
        self.username_input.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.username_input.setText("")
        self.username_input.setObjectName("username_input")
        self.password_input = QtWidgets.QLineEdit(Dialog)
        self.password_input.setGeometry(QtCore.QRect(210, 280, 351, 41))
        self.password_input.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.password_input.setText("")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.loginbutton = QtWidgets.QPushButton(Dialog)
        self.loginbutton.setGeometry(QtCore.QRect(460, 370, 101, 31))
        self.loginbutton.setStyleSheet("background-color: rgb(156, 208, 93);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.loginbutton.setObjectName("loginbutton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(180, 150, 251, 21))
        self.label_4.setObjectName("label_4")
        self.createbutton = QtWidgets.QPushButton(Dialog)
        self.createbutton.setGeometry(QtCore.QRect(460, 330, 101, 31))
        self.createbutton.setStyleSheet("background-color: rgb(156, 208, 93);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.createbutton.setObjectName("createbutton")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(130, 70, 421, 61))
        self.label_5.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(180, 330, 271, 31))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(150, 370, 311, 31))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Username : "))
        self.label_3.setText(_translate("Dialog", "Password:"))
        self.loginbutton.setText(_translate("Dialog", "LOGIN"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" text-decoration: underline;\">PROYECT BY JARED AND MOU </span></p></body></html>"))
        self.createbutton.setText(_translate("Dialog", "CREATE"))
        self.label_5.setText(_translate("Dialog", "San Pablo Pharmacy ⚕️"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:7pt; font-style:italic; text-decoration: underline;\">Don\'t have any account, click &quot;CREATE&quot; ➡️</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:7pt; font-style:italic; text-decoration: underline;\">You already have an account, click on &quot;LOGIN&quot;➡️</span></p></body></html>"))
