# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jared\OneDrive\Documentos\OBEJETOS\PharmacyProject\menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(620, 480)
        Dialog.setStyleSheet("background-color: rgb(23, 136, 211)")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(180, 70, 261, 71))
        self.label.setStyleSheet("color: rgb(255, 255, 255);font-size:28pt;")
        self.label.setObjectName("label")
        self.addbutton = QtWidgets.QPushButton(Dialog)
        self.addbutton.setGeometry(QtCore.QRect(220, 160, 171, 61))
        self.addbutton.setStyleSheet("background-color: rgb(156, 208, 93);\n"
"color: rgb(255, 255, 255);")
        self.addbutton.setObjectName("addbutton")
        self.addsalebutton = QtWidgets.QPushButton(Dialog)
        self.addsalebutton.setGeometry(QtCore.QRect(220, 240, 171, 61))
        self.addsalebutton.setStyleSheet("background-color: rgb(156, 208, 93);\n"
"color: rgb(255, 255, 255);")
        self.addsalebutton.setObjectName("addsalebutton")
        self.reportbutton = QtWidgets.QPushButton(Dialog)
        self.reportbutton.setGeometry(QtCore.QRect(220, 320, 171, 61))
        self.reportbutton.setStyleSheet("background-color: rgb(156, 208, 93);\n"
"color: rgb(255, 255, 255);")
        self.reportbutton.setObjectName("reportbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; text-decoration: underline;\">OPTIONS MENU</span></p></body></html>"))
        self.addbutton.setText(_translate("Dialog", "ADD PRODUCTS"))
        self.addsalebutton.setText(_translate("Dialog", "CREATE  SALE "))
        self.reportbutton.setText(_translate("Dialog", "REPORTS "))
